name: test

on:
  - push
  - pull_request

jobs:

  perl-versions:
    runs-on: ubuntu-latest
    name: List Perl versions
    outputs:
      perl-versions: ${{ steps.action.outputs.perl-versions }}
    steps:
      - id: action
        uses: perl-actions/perl-versions@v1
        with:
          since-perl: v5.10
          with-devel: true

  linux:
    runs-on: ubuntu-latest
    needs: [perl-versions]
    defaults:
      run:
        shell: 'script -q -e -c "bash {0}"' # create TTY so that -t STDIN works
    strategy:
      fail-fast: false
      matrix:
        perl-version: ${{ fromJson(needs.perl-versions.outputs.perl-versions).map( i => i + '-buster' ) }}
    container: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          perl App-cpanminus/cpanm -nq App::cpanminus
          cpanm -nq LWP::Protocol::https
          (cd App-cpanminus && cpanm -nq --installdeps --with-develop --with-recommends --with-suggests .)
          (cd Menlo && cpanm -nq --installdeps --with-develop --with-recommends --with-suggests .)
      - name: Run Tests
        run: (cd App-cpanminus && prove -lr xt -j9)
